In [1]:
import pandas as pd
import numpy as np

from sklearn import svm
from sklearn import preprocessing

from matplotlib import pyplot as plt

# 1. 读取数据

### 1.1 读取 csv 文件

In [2]:
data_train = pd.read_csv("train.csv")
data_test = pd.read_csv("test.csv")

### 1.2 查看数据信息

In [3]:
data_train.head()       # 头部数据

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       8       0       0       0       0       0       1       1       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       1       0       0       0       0       0       0       2       3   
3   4       0       0       0       0       0       0       0       1       2   
4   5       0       0       5       8       0       0       0       0       1   

    ...     feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0   ...           0        1        1        1        0        0        1   
1   ...           0        1        0        0        0        6        0   
2   ...           1        0        0        1        0        0        0   
3   ...           3        0        1        0        0        3        0   
4   ...           0        0        0        0        1        0        0   

   feat_92  feat_93   target  
0        0        0  Class_4  
1        0        0  Class_8  
2        0        0  Class_6  
3        0        0  Class_8  
4        0        0  Class_6  

[5 rows x 95 columns]

In [4]:
data_train.tail()       # 尾部数据

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  \
49497  49498       0       0       0       0       0       0       0       1   
49498  49499       0       0       0       1       0       0       0       0   
49499  49500       0       0       0       0       0       0       0       0   
49500  49501       0       0       0       0       0       0       0       4   
49501  49502       0       0       0       0       0       0       0       0   

       feat_9   ...     feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  \
49497       0   ...           0        1        0        0        0        0   
49498       0   ...           0        0        0        0        1        0   
49499       0   ...           0        1        0        3        0        0   
49500       0   ...           0        0        0        0        1        0   
49501       1   ...           1        1        0        1        0        0   

       feat_91  feat_92  feat_93   target  
49497        0        0        0  Class_8  
49498        0        0        0  Class_5  
49499        0        0        0  Class_2  
49500        2        0        0  Class_1  
49501        0        0        0  Class_2  

[5 rows x 95 columns]

In [5]:
data_train.info()       # 数据信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49502 entries, 0 to 49501
Data columns (total 95 columns):
id         49502 non-null int64
feat_1     49502 non-null int64
feat_2     49502 non-null int64
feat_3     49502 non-null int64
feat_4     49502 non-null int64
feat_5     49502 non-null int64
feat_6     49502 non-null int64
feat_7     49502 non-null int64
feat_8     49502 non-null int64
feat_9     49502 non-null int64
feat_10    49502 non-null int64
feat_11    49502 non-null int64
feat_12    49502 non-null int64
feat_13    49502 non-null int64
feat_14    49502 non-null int64
feat_15    49502 non-null int64
feat_16    49502 non-null int64
feat_17    49502 non-null int64
feat_18    49502 non-null int64
feat_19    49502 non-null int64
feat_20    49502 non-null int64
feat_21    49502 non-null int64
feat_22    49502 non-null int64
feat_23    49502 non-null int64
feat_24    49502 non-null int64
feat_25    49502 non-null int64
feat_26    49502 non-null int64
feat_27    49502 non-null i

In [10]:
pd.options.display.float_format = '{:,.2f}'.format     # 设置 pandas 数据显示格式：2位浮点数
data_train.describe()   # 统计特性

id    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
count 49,502.00 49,502.00 49,502.00 49,502.00 49,502.00 49,502.00 49,502.00   
mean  24,751.50      0.39      0.26      0.91      0.78      0.07      0.03   
std   14,290.14      1.54      1.27      2.95      2.79      0.44      0.22   
min        1.00      0.00      0.00      0.00      0.00      0.00      0.00   
25%   12,376.25      0.00      0.00      0.00      0.00      0.00      0.00   
50%   24,751.50      0.00      0.00      0.00      0.00      0.00      0.00   
75%   37,126.75      0.00      0.00      0.00      0.00      0.00      0.00   
max   49,502.00     61.00     51.00     64.00     68.00     19.00     10.00   

         feat_7    feat_8    feat_9    ...      feat_84   feat_85   feat_86  \
count 49,502.00 49,502.00 49,502.00    ...    49,502.00 49,502.00 49,502.00   
mean       0.19      0.67      1.00    ...         0.07      0.53      1.14   
std        1.02      2.25      3.43    ...         1.17      1.90      2.72   
min        0.00      0.00      0.00    ...         0.00      0.00      0.00   
25%        0.00      0.00      0.00    ...         0.00      0.00      0.00   
50%        0.00      0.00      0.00    ...         0.00      0.00      0.00   
75%        0.00      1.00      0.00    ...         0.00      0.00      1.00   
max       38.00     75.00     43.00    ...        76.00     55.00     65.00   

        feat_87   feat_88   feat_89   feat_90   feat_91   feat_92   feat_93  
count 49,502.00 49,502.00 49,502.00 49,502.00 49,502.00 49,502.00 49,502.00  
mean       0.39      0.87      0.46      0.80      0.27      0.38      0.13  
std        1.59      2.12      1.55      4.52      2.06      0.99      1.19  
min        0.00      0.00      0.00      0.00      0.00      0.00      0.00  
25%        0.00      0.00      0.00      0.00      0.00      0.00      0.00  
50%        0.00      0.00      0.00      0.00      0.00      0.00      0.00  
75%        0.00      1.00      0.00      0.00      0.00      0.00      0.00  
max       67.00     30.00     61.00    130.00     48.00     19.00     87.00  

[8 rows x 94 columns]

In [12]:
data_train.shape        # 总体尺寸

(49502, 95)

### 1.3 数据向量化

共有 9 类商品，93项特征，49501条样本

In [50]:
y = data_train["target"]
y_train = np.zeros([len(y), 9], dtype = np.int8)
for i, item in enumerate(y):
    index = int(item[-1]) - 1
    y_train[i, index] = 1
y_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int8)

In [51]:
x_train = data_train.values[:,1:-1].astype(np.int32)
x_test = data_test.values[:,1:-1].astype(np.int32)
x_train

array([[8, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# 2. 数据预处理

### 2.1 缺失数据处理

In [56]:
rows, cols = x_train.shape
for i in range(rows):
    for j in range(cols):
        if x_train[i,j] == np.nan:
            print(x_train[j], j)
# 无缺失数据

### 2.2 归一化（可选）

In [54]:
mean = x_train.mean(axis=0)     # 计算各个特征的均值、方差
std = x_train.std(axis=0)
x_train_norm = (x_train - mean)/std
x_train_norm

array([[ 4.93168218, -0.20723124, -0.30726674, ...,  0.3542665 ,
        -0.38696306, -0.10514962],
       [-0.25139528, -0.20723124, -0.30726674, ..., -0.13023179,
        -0.38696306, -0.10514962],
       [ 0.39648941, -0.20723124, -0.30726674, ..., -0.13023179,
        -0.38696306, -0.10514962],
       ...,
       [-0.25139528, -0.20723124, -0.30726674, ..., -0.13023179,
        -0.38696306, -0.10514962],
       [-0.25139528, -0.20723124, -0.30726674, ...,  0.83876479,
        -0.38696306, -0.10514962],
       [-0.25139528, -0.20723124, -0.30726674, ..., -0.13023179,
        -0.38696306, -0.10514962]])

# 3. 建模

# 数据评价

$$logloss = - \frac{1}{N} \sum_{i=1}^{N} \sum_{j=1}^{M} y_{i,j} \; log(p_{i,j})  \tag{1}$$

其中$N$代表测试数据集中的商品数量，$i,j$分别是商品和类别的索引。当商品$i$属于类别$j$时，$y_{i,j}=1$，否则为0。其中，$p_{i,j}$是预测的概率。

**注意：** 由于存在自然对数，故规定$p = max(min(p,1-10^{-15}) ,\; 10^{-15})$

In [ ]:
def evaluation(label,pred_label):
    num = len(label)
    logloss = 0.0
    for i in range(num):
        p = max(min(pred_label[i][label[i]-1],1-10**(-15)),10**(-15))
        logloss += np.log(p)
    logloss = -1*logloss/num
    return logloss

# 4. 预测

In [ ]:
test_y = model.predict(test_x)
answer = pd.read_csv(open("sampleSubmission.csv"))
class_list = ["Class_1","Class_2","Class_3","Class_4","Class_5","Class_6","Class_7","Class_8","Class_9"]
answer[class_list] = answer[class_list].astype(float)

# 5. 结果保存

In [35]:
j = 0
for class_name in class_list:
    answer[class_name] = test_y[:, j]
    j += 1
answer.to_csv("submission.csv",index=False)